---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
  - name: Test
    type: tester
    script: |-
      #!/bin/bash
      npm install
      XUNIT_FILE=tests/TEST-items.xml node_modules/mocha/bin/mocha -R spec-xunit-file tests/server/items.spec.js
    enable_tests: true
    test_file_pattern: tests/TEST-*.xml
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy Stage
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      # Publish catalogAPI
      if ! cf service catalogAPI > /dev/null; then
        cf cups catalogAPI
      fi

      # Push app
      export CF_APP_NAME="$CF_APP"
      cf push "${CF_APP_NAME}"

      # Update catalogAPI
      HOST=http://$(cf app $CF_APP_NAME | grep urls: | awk '{print $2}')
      cf uups catalogAPI -p '{"host":"'$HOST'"}'
